import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function firstposts() {
    return (

        <div className={styles.container}>
    <Head>
        <title>NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
            <h1>FirstPosts</h1>
            <Link href="/"><h2>戻る</h2></Link>
        </div>
    );
}